version: "2"
run:
  tests: false

linters:
  default: fast
  # Start simple: only "critical" or high signal linters
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
