version: "2"
run:
  tests: false

linters:
  default: standard
  # Start simple: only "critical" or high signal linters
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  disable:
    - depguard

  settings:
    errcheck:
      exclude-functions:
        - (*.Close)
        - (*net/http.Response).Body.Close
        - (*database/sql.DB).Close
        - (io.ReadCloser).Close
