# Use an official Node.js runtime as a parent image
FROM node:22.19.0-alpine

# Set the working directory in the container
WORKDIR /app/ui

# Copy package.json and package-lock.json
COPY ui/package.json ui/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the UI code
COPY ui/ .

# Expose the Vite port
EXPOSE 5173

# Command to run the Vite dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
