version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - .:/app
      - /app/node_modules # mask node_modules
      - /app/tmp # mask tmp
    command: air -c .air.toml

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules
    command: npm run dev -- --host 0.0.0.0
