// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, system_prompt, tools, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	SystemPrompt string       `json:"system_prompt"`
	Tools        string       `json:"tools"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.SystemPrompt,
		arg.Tools,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, system_prompt, tools, created_at, updated_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemPrompt,
		&i.Tools,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, system_prompt, tools, created_at, updated_at FROM agents WHERE name = ?
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SystemPrompt,
		&i.Tools,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, system_prompt, tools, created_at, updated_at FROM agents
ORDER BY name ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SystemPrompt,
			&i.Tools,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents
SET name = ?, system_prompt = ?, tools = ?, updated_at = ?
WHERE id = ?
`

type UpdateAgentParams struct {
	Name         string       `json:"name"`
	SystemPrompt string       `json:"system_prompt"`
	Tools        string       `json:"tools"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	ID           string       `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.ExecContext(ctx, updateAgent,
		arg.Name,
		arg.SystemPrompt,
		arg.Tools,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
