// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentLog = `-- name: CreateAgentLog :exec
INSERT INTO agent_logs (task_id, level, message) VALUES ($1, $2, $3)
`

type CreateAgentLogParams struct {
	TaskID  string      `json:"task_id"`
	Level   pgtype.Text `json:"level"`
	Message string      `json:"message"`
}

func (q *Queries) CreateAgentLog(ctx context.Context, arg CreateAgentLogParams) error {
	_, err := q.db.Exec(ctx, createAgentLog, arg.TaskID, arg.Level, arg.Message)
	return err
}

const getAgentLogsByTask = `-- name: GetAgentLogsByTask :many
SELECT id, task_id, level, message, created_at FROM agent_logs WHERE task_id = $1 ORDER BY id ASC
`

func (q *Queries) GetAgentLogsByTask(ctx context.Context, taskID string) ([]AgentLog, error) {
	rows, err := q.db.Query(ctx, getAgentLogsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentLog{}
	for rows.Next() {
		var i AgentLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
