// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_runs.sql

package sqlc

import (
	"context"
)

const createAgentRun = `-- name: CreateAgentRun :exec
INSERT INTO agent_runs (id, task_id, agent_backend, prompt, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAgentRunParams struct {
	ID           string `json:"id"`
	TaskID       string `json:"task_id"`
	AgentBackend string `json:"agent_backend"`
	Prompt       string `json:"prompt"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, createAgentRun,
		arg.ID,
		arg.TaskID,
		arg.AgentBackend,
		arg.Prompt,
		arg.CreatedAt,
	)
	return err
}

const deleteAgentRunsByTask = `-- name: DeleteAgentRunsByTask :exec
DELETE FROM agent_runs WHERE task_id = ?
`

func (q *Queries) DeleteAgentRunsByTask(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentRunsByTask, taskID)
	return err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, task_id, prompt, agent_backend, summary_message_id, cost, message_count, prompt_tokens, completion_tokens, completed_at, created_at, updated_at FROM agent_runs WHERE id = ?
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Prompt,
		&i.AgentBackend,
		&i.SummaryMessageID,
		&i.Cost,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRun = `-- name: GetLatestRun :one
SELECT id, task_id, prompt, agent_backend, summary_message_id, cost, message_count, prompt_tokens, completion_tokens, completed_at, created_at, updated_at FROM agent_runs
WHERE task_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRun(ctx context.Context, taskID string) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestRun, taskID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Prompt,
		&i.AgentBackend,
		&i.SummaryMessageID,
		&i.Cost,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentRunsByTask = `-- name: ListAgentRunsByTask :many
SELECT id, task_id, prompt, agent_backend, summary_message_id, cost, message_count, prompt_tokens, completion_tokens, completed_at, created_at, updated_at FROM agent_runs
WHERE task_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgentRunsByTask(ctx context.Context, taskID string) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Prompt,
			&i.AgentBackend,
			&i.SummaryMessageID,
			&i.Cost,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
