// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAuth = `-- name: CreateAuth :one
INSERT INTO auth (machine_id, jwt_token, user_id, email, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, machine_id, jwt_token, user_id, email, expires_at, created_at, updated_at
`

type CreateAuthParams struct {
	MachineID string         `json:"machine_id"`
	JwtToken  string         `json:"jwt_token"`
	UserID    string         `json:"user_id"`
	Email     sql.NullString `json:"email"`
	ExpiresAt int64          `json:"expires_at"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) CreateAuth(ctx context.Context, arg CreateAuthParams) (Auth, error) {
	row := q.db.QueryRowContext(ctx, createAuth,
		arg.MachineID,
		arg.JwtToken,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.JwtToken,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuth = `-- name: DeleteAuth :exec
DELETE FROM auth WHERE id = ?
`

func (q *Queries) DeleteAuth(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAuth, id)
	return err
}

const deleteAuthByMachine = `-- name: DeleteAuthByMachine :exec
DELETE FROM auth WHERE machine_id = ?
`

func (q *Queries) DeleteAuthByMachine(ctx context.Context, machineID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthByMachine, machineID)
	return err
}

const getAuth = `-- name: GetAuth :one
SELECT id, machine_id, jwt_token, user_id, email, expires_at, created_at, updated_at FROM auth WHERE machine_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetAuth(ctx context.Context, machineID string) (Auth, error) {
	row := q.db.QueryRowContext(ctx, getAuth, machineID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.JwtToken,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthByMachineID = `-- name: GetAuthByMachineID :one
SELECT id, machine_id, jwt_token, user_id, email, expires_at, created_at, updated_at FROM auth WHERE machine_id = ? LIMIT 1
`

func (q *Queries) GetAuthByMachineID(ctx context.Context, machineID string) (Auth, error) {
	row := q.db.QueryRowContext(ctx, getAuthByMachineID, machineID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.JwtToken,
		&i.UserID,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAuth = `-- name: UpdateAuth :exec
UPDATE auth SET jwt_token = ?, expires_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateAuthParams struct {
	JwtToken  string `json:"jwt_token"`
	ExpiresAt int64  `json:"expires_at"`
	UpdatedAt int64  `json:"updated_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateAuth(ctx context.Context, arg UpdateAuthParams) error {
	_, err := q.db.ExecContext(ctx, updateAuth,
		arg.JwtToken,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
