// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGitHubConnection = `-- name: CreateGitHubConnection :exec
INSERT INTO github_connections (id, user_id, type, login, avatar_url, token, scope, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateGitHubConnectionParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Login     string             `json:"login"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Token     string             `json:"token"`
	Scope     pgtype.Text        `json:"scope"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGitHubConnection(ctx context.Context, arg CreateGitHubConnectionParams) error {
	_, err := q.db.Exec(ctx, createGitHubConnection,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Login,
		arg.AvatarUrl,
		arg.Token,
		arg.Scope,
		arg.CreatedAt,
	)
	return err
}

const deleteAllGitHubConnections = `-- name: DeleteAllGitHubConnections :execresult
DELETE FROM github_connections WHERE user_id = $1
`

func (q *Queries) DeleteAllGitHubConnections(ctx context.Context, userID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAllGitHubConnections, userID)
}

const getActiveGitHubConnection = `-- name: GetActiveGitHubConnection :one
SELECT id, user_id, type, login, avatar_url, token, scope, created_at FROM github_connections WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveGitHubConnection(ctx context.Context, userID string) (GithubConnection, error) {
	row := q.db.QueryRow(ctx, getActiveGitHubConnection, userID)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Login,
		&i.AvatarUrl,
		&i.Token,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}
