// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGithubConnection = `-- name: CreateGithubConnection :one
INSERT INTO github_connections (
    id, github_user_id, access_token, username, avatar_url, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, github_user_id, access_token, username, avatar_url, created_at, updated_at
`

type CreateGithubConnectionParams struct {
	ID           string         `json:"id"`
	GithubUserID string         `json:"github_user_id"`
	AccessToken  string         `json:"access_token"`
	Username     string         `json:"username"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateGithubConnection(ctx context.Context, arg CreateGithubConnectionParams) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, createGithubConnection,
		arg.ID,
		arg.GithubUserID,
		arg.AccessToken,
		arg.Username,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.AccessToken,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    id, connection_id, name, full_name, owner, is_private, html_url, clone_url, local_path, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, connection_id, name, full_name, owner, is_private, html_url, clone_url, local_path, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID           string         `json:"id"`
	ConnectionID string         `json:"connection_id"`
	Name         string         `json:"name"`
	FullName     string         `json:"full_name"`
	Owner        string         `json:"owner"`
	IsPrivate    bool           `json:"is_private"`
	HtmlUrl      string         `json:"html_url"`
	CloneUrl     string         `json:"clone_url"`
	LocalPath    sql.NullString `json:"local_path"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository,
		arg.ID,
		arg.ConnectionID,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.IsPrivate,
		arg.HtmlUrl,
		arg.CloneUrl,
		arg.LocalPath,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.CloneUrl,
		&i.LocalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGithubConnection = `-- name: DeleteGithubConnection :exec
DELETE FROM github_connections WHERE id = ?
`

func (q *Queries) DeleteGithubConnection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGithubConnection, id)
	return err
}

const deleteRepositoriesByConnection = `-- name: DeleteRepositoriesByConnection :exec
DELETE FROM repositories WHERE connection_id = ?
`

func (q *Queries) DeleteRepositoriesByConnection(ctx context.Context, connectionID string) error {
	_, err := q.db.ExecContext(ctx, deleteRepositoriesByConnection, connectionID)
	return err
}

const getGithubConnection = `-- name: GetGithubConnection :one
SELECT id, github_user_id, access_token, username, avatar_url, created_at, updated_at FROM github_connections LIMIT 1
`

func (q *Queries) GetGithubConnection(ctx context.Context) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, getGithubConnection)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.AccessToken,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubConnectionByID = `-- name: GetGithubConnectionByID :one
SELECT id, github_user_id, access_token, username, avatar_url, created_at, updated_at FROM github_connections WHERE id = ?
`

func (q *Queries) GetGithubConnectionByID(ctx context.Context, id string) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, getGithubConnectionByID, id)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.AccessToken,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, connection_id, name, full_name, owner, is_private, html_url, clone_url, local_path, created_at, updated_at FROM repositories WHERE id = ?
`

func (q *Queries) GetRepository(ctx context.Context, id string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Name,
		&i.FullName,
		&i.Owner,
		&i.IsPrivate,
		&i.HtmlUrl,
		&i.CloneUrl,
		&i.LocalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, connection_id, name, full_name, owner, is_private, html_url, clone_url, local_path, created_at, updated_at FROM repositories WHERE connection_id = ? ORDER BY full_name ASC
`

func (q *Queries) ListRepositories(ctx context.Context, connectionID string) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Name,
			&i.FullName,
			&i.Owner,
			&i.IsPrivate,
			&i.HtmlUrl,
			&i.CloneUrl,
			&i.LocalPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGithubConnection = `-- name: UpdateGithubConnection :one
UPDATE github_connections
SET access_token = ?, username = ?, avatar_url = ?, updated_at = ?
WHERE id = ?
RETURNING id, github_user_id, access_token, username, avatar_url, created_at, updated_at
`

type UpdateGithubConnectionParams struct {
	AccessToken string         `json:"access_token"`
	Username    string         `json:"username"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateGithubConnection(ctx context.Context, arg UpdateGithubConnectionParams) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, updateGithubConnection,
		arg.AccessToken,
		arg.Username,
		arg.AvatarUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.AccessToken,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
