// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createGitHubConnection = `-- name: CreateGitHubConnection :exec
INSERT INTO github_connections (id, type, login, avatar_url, token, scope, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateGitHubConnectionParams struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Login     string         `json:"login"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Token     string         `json:"token"`
	Scope     sql.NullString `json:"scope"`
	CreatedAt int64          `json:"created_at"`
}

func (q *Queries) CreateGitHubConnection(ctx context.Context, arg CreateGitHubConnectionParams) error {
	_, err := q.db.ExecContext(ctx, createGitHubConnection,
		arg.ID,
		arg.Type,
		arg.Login,
		arg.AvatarUrl,
		arg.Token,
		arg.Scope,
		arg.CreatedAt,
	)
	return err
}

const deleteAllGitHubConnections = `-- name: DeleteAllGitHubConnections :execresult
DELETE FROM github_connections
`

func (q *Queries) DeleteAllGitHubConnections(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllGitHubConnections)
}

const getActiveGitHubConnection = `-- name: GetActiveGitHubConnection :one
SELECT id, type, login, avatar_url, token, scope, created_at FROM github_connections ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveGitHubConnection(ctx context.Context) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, getActiveGitHubConnection)
	var i GithubConnection
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Login,
		&i.AvatarUrl,
		&i.Token,
		&i.Scope,
		&i.CreatedAt,
	)
	return i, err
}
