// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: machines.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMachine = `-- name: CreateMachine :exec
INSERT INTO machines (id, name, mode, capabilities, last_seen_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateMachineParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Mode         string         `json:"mode"`
	Capabilities sql.NullString `json:"capabilities"`
	LastSeenAt   sql.NullTime   `json:"last_seen_at"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) error {
	_, err := q.db.ExecContext(ctx, createMachine,
		arg.ID,
		arg.Name,
		arg.Mode,
		arg.Capabilities,
		arg.LastSeenAt,
	)
	return err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE id = ?
`

func (q *Queries) DeleteMachine(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, id)
	return err
}

const getDefaultMachine = `-- name: GetDefaultMachine :one
SELECT id, name, mode, capabilities, last_seen_at FROM machines
WHERE mode = 'local'
LIMIT 1
`

func (q *Queries) GetDefaultMachine(ctx context.Context) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getDefaultMachine)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Capabilities,
		&i.LastSeenAt,
	)
	return i, err
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, mode, capabilities, last_seen_at FROM machines WHERE id = ?
`

func (q *Queries) GetMachine(ctx context.Context, id string) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Capabilities,
		&i.LastSeenAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, name, mode, capabilities, last_seen_at FROM machines
ORDER BY name ASC
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Capabilities,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinesByMode = `-- name: ListMachinesByMode :many
SELECT id, name, mode, capabilities, last_seen_at FROM machines
WHERE mode = ?
ORDER BY name ASC
`

func (q *Queries) ListMachinesByMode(ctx context.Context, mode string) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachinesByMode, mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Capabilities,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMachineCapabilities = `-- name: UpdateMachineCapabilities :exec
UPDATE machines SET capabilities = ? WHERE id = ?
`

type UpdateMachineCapabilitiesParams struct {
	Capabilities sql.NullString `json:"capabilities"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateMachineCapabilities(ctx context.Context, arg UpdateMachineCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineCapabilities, arg.Capabilities, arg.ID)
	return err
}

const updateMachineLastSeen = `-- name: UpdateMachineLastSeen :exec
UPDATE machines SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateMachineLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateMachineLastSeen, id)
	return err
}
