// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (id, name, mode, capabilities, created_at, updated_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, mode, capabilities, last_seen_at, created_at, updated_at
`

type CreateMachineParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Mode         string         `json:"mode"`
	Capabilities sql.NullString `json:"capabilities"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	LastSeenAt   int64          `json:"last_seen_at"`
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRowContext(ctx, createMachine,
		arg.ID,
		arg.Name,
		arg.Mode,
		arg.Capabilities,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSeenAt,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines WHERE id = ?
`

func (q *Queries) DeleteMachine(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, id)
	return err
}

const getAllMachines = `-- name: GetAllMachines :many
SELECT id, name, mode, capabilities, last_seen_at, created_at, updated_at FROM machines ORDER BY created_at DESC
`

func (q *Queries) GetAllMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, getAllMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Machine{}
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, mode, capabilities, last_seen_at, created_at, updated_at FROM machines WHERE id = ? LIMIT 1
`

func (q *Queries) GetMachine(ctx context.Context, id string) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mode,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMachineLastSeen = `-- name: UpdateMachineLastSeen :exec
UPDATE machines SET last_seen_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateMachineLastSeenParams struct {
	LastSeenAt int64  `json:"last_seen_at"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateMachineLastSeen(ctx context.Context, arg UpdateMachineLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineLastSeen, arg.LastSeenAt, arg.UpdatedAt, arg.ID)
	return err
}
