// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type AgentLog struct {
	ID        int64          `json:"id"`
	TaskID    string         `json:"task_id"`
	Level     sql.NullString `json:"level"`
	Message   string         `json:"message"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type GithubConnection struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Login     string         `json:"login"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Token     string         `json:"token"`
	Scope     sql.NullString `json:"scope"`
	CreatedAt int64          `json:"created_at"`
}

type Project struct {
	ID          string `json:"id"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
	CreatedAt   int64  `json:"created_at"`
}

type Task struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	Title          string         `json:"title"`
	Intent         string         `json:"intent"`
	Status         string         `json:"status"`
	Position       sql.NullInt64  `json:"position"`
	AgentOutput    sql.NullString `json:"agent_output"`
	GitDiff        sql.NullString `json:"git_diff"`
	MessageHistory sql.NullString `json:"message_history"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type UserSetting struct {
	UserID        string         `json:"user_id"`
	OpenrouterKey sql.NullString `json:"openrouter_key"`
	ZaiKey        sql.NullString `json:"zai_key"`
	AnthropicKey  sql.NullString `json:"anthropic_key"`
	OpenaiKey     sql.NullString `json:"openai_key"`
	AgentBackend  sql.NullString `json:"agent_backend"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
