// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: oauth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanupExpiredOAuthAttempts = `-- name: CleanupExpiredOAuthAttempts :exec
DELETE FROM oauth_login_attempts WHERE created_at < ?
`

func (q *Queries) CleanupExpiredOAuthAttempts(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredOAuthAttempts, createdAt)
	return err
}

const createMachineIdentity = `-- name: CreateMachineIdentity :exec
INSERT INTO machine_identity (machine_id, user_id, subdomain, tunnel_provider, tunnel_token, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMachineIdentityParams struct {
	MachineID      string `json:"machine_id"`
	UserID         string `json:"user_id"`
	Subdomain      string `json:"subdomain"`
	TunnelProvider string `json:"tunnel_provider"`
	TunnelToken    string `json:"tunnel_token"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) CreateMachineIdentity(ctx context.Context, arg CreateMachineIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createMachineIdentity,
		arg.MachineID,
		arg.UserID,
		arg.Subdomain,
		arg.TunnelProvider,
		arg.TunnelToken,
		arg.CreatedAt,
	)
	return err
}

const createOAuthLoginAttempt = `-- name: CreateOAuthLoginAttempt :exec
INSERT INTO oauth_login_attempts (state, code_verifier, created_at)
VALUES (?, ?, ?)
`

type CreateOAuthLoginAttemptParams struct {
	State        string `json:"state"`
	CodeVerifier string `json:"code_verifier"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateOAuthLoginAttempt(ctx context.Context, arg CreateOAuthLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthLoginAttempt, arg.State, arg.CodeVerifier, arg.CreatedAt)
	return err
}

const deleteOAuthLoginAttempt = `-- name: DeleteOAuthLoginAttempt :exec
DELETE FROM oauth_login_attempts WHERE state = ?
`

func (q *Queries) DeleteOAuthLoginAttempt(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthLoginAttempt, state)
	return err
}

const getMachineByUserID = `-- name: GetMachineByUserID :one
SELECT machine_id, user_id, subdomain, tunnel_provider, tunnel_token, created_at, last_seen_at
FROM machine_identity
WHERE user_id = ?
`

func (q *Queries) GetMachineByUserID(ctx context.Context, userID string) (MachineIdentity, error) {
	row := q.db.QueryRowContext(ctx, getMachineByUserID, userID)
	var i MachineIdentity
	err := row.Scan(
		&i.MachineID,
		&i.UserID,
		&i.Subdomain,
		&i.TunnelProvider,
		&i.TunnelToken,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getMachineIdentity = `-- name: GetMachineIdentity :one
SELECT machine_id, user_id, subdomain, tunnel_provider, tunnel_token, created_at, last_seen_at
FROM machine_identity
WHERE machine_id = ?
`

func (q *Queries) GetMachineIdentity(ctx context.Context, machineID string) (MachineIdentity, error) {
	row := q.db.QueryRowContext(ctx, getMachineIdentity, machineID)
	var i MachineIdentity
	err := row.Scan(
		&i.MachineID,
		&i.UserID,
		&i.Subdomain,
		&i.TunnelProvider,
		&i.TunnelToken,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getOAuthLoginAttempt = `-- name: GetOAuthLoginAttempt :one
SELECT state, code_verifier, created_at
FROM oauth_login_attempts
WHERE state = ?
`

type GetOAuthLoginAttemptRow struct {
	State        string `json:"state"`
	CodeVerifier string `json:"code_verifier"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) GetOAuthLoginAttempt(ctx context.Context, state string) (GetOAuthLoginAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthLoginAttempt, state)
	var i GetOAuthLoginAttemptRow
	err := row.Scan(&i.State, &i.CodeVerifier, &i.CreatedAt)
	return i, err
}

const updateMachineIdentityLastSeen = `-- name: UpdateMachineIdentityLastSeen :exec
UPDATE machine_identity SET last_seen_at = ? WHERE machine_id = ?
`

type UpdateMachineIdentityLastSeenParams struct {
	LastSeenAt sql.NullInt64 `json:"last_seen_at"`
	MachineID  string        `json:"machine_id"`
}

func (q *Queries) UpdateMachineIdentityLastSeen(ctx context.Context, arg UpdateMachineIdentityLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineIdentityLastSeen, arg.LastSeenAt, arg.MachineID)
	return err
}

const upsertMachineIdentity = `-- name: UpsertMachineIdentity :one
INSERT INTO machine_identity (machine_id, user_id, subdomain, tunnel_provider, tunnel_token, created_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(machine_id) DO UPDATE SET
    user_id = excluded.user_id,
    subdomain = excluded.subdomain,
    tunnel_provider = excluded.tunnel_provider,
    tunnel_token = excluded.tunnel_token,
    last_seen_at = excluded.last_seen_at
RETURNING machine_id, user_id, subdomain, tunnel_provider, tunnel_token, created_at, last_seen_at
`

type UpsertMachineIdentityParams struct {
	MachineID      string        `json:"machine_id"`
	UserID         string        `json:"user_id"`
	Subdomain      string        `json:"subdomain"`
	TunnelProvider string        `json:"tunnel_provider"`
	TunnelToken    string        `json:"tunnel_token"`
	CreatedAt      int64         `json:"created_at"`
	LastSeenAt     sql.NullInt64 `json:"last_seen_at"`
}

func (q *Queries) UpsertMachineIdentity(ctx context.Context, arg UpsertMachineIdentityParams) (MachineIdentity, error) {
	row := q.db.QueryRowContext(ctx, upsertMachineIdentity,
		arg.MachineID,
		arg.UserID,
		arg.Subdomain,
		arg.TunnelProvider,
		arg.TunnelToken,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	var i MachineIdentity
	err := row.Scan(
		&i.MachineID,
		&i.UserID,
		&i.Subdomain,
		&i.TunnelProvider,
		&i.TunnelToken,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
