// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: openai_connector.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanupExpiredConnectorOAuthAttempts = `-- name: CleanupExpiredConnectorOAuthAttempts :exec
DELETE FROM connector_oauth_attempts
WHERE connector = ? AND created_at < ?
`

type CleanupExpiredConnectorOAuthAttemptsParams struct {
	Connector string `json:"connector"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CleanupExpiredConnectorOAuthAttempts(ctx context.Context, arg CleanupExpiredConnectorOAuthAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredConnectorOAuthAttempts, arg.Connector, arg.CreatedAt)
	return err
}

const createConnectorOAuthAttempt = `-- name: CreateConnectorOAuthAttempt :exec
INSERT INTO connector_oauth_attempts (connector, state, code_verifier, created_at)
VALUES (?, ?, ?, ?)
`

type CreateConnectorOAuthAttemptParams struct {
	Connector    string `json:"connector"`
	State        string `json:"state"`
	CodeVerifier string `json:"code_verifier"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateConnectorOAuthAttempt(ctx context.Context, arg CreateConnectorOAuthAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createConnectorOAuthAttempt,
		arg.Connector,
		arg.State,
		arg.CodeVerifier,
		arg.CreatedAt,
	)
	return err
}

const deleteConnectorAuth = `-- name: DeleteConnectorAuth :exec
DELETE FROM connector_auth
WHERE connector = ?
`

func (q *Queries) DeleteConnectorAuth(ctx context.Context, connector string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorAuth, connector)
	return err
}

const deleteConnectorOAuthAttempt = `-- name: DeleteConnectorOAuthAttempt :exec
DELETE FROM connector_oauth_attempts
WHERE connector = ? AND state = ?
`

type DeleteConnectorOAuthAttemptParams struct {
	Connector string `json:"connector"`
	State     string `json:"state"`
}

func (q *Queries) DeleteConnectorOAuthAttempt(ctx context.Context, arg DeleteConnectorOAuthAttemptParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorOAuthAttempt, arg.Connector, arg.State)
	return err
}

const getConnectorAuth = `-- name: GetConnectorAuth :one
SELECT connector, access_token, refresh_token, account_id, metadata_json, expires_at, connected_at, updated_at
FROM connector_auth
WHERE connector = ?
`

func (q *Queries) GetConnectorAuth(ctx context.Context, connector string) (ConnectorAuth, error) {
	row := q.db.QueryRowContext(ctx, getConnectorAuth, connector)
	var i ConnectorAuth
	err := row.Scan(
		&i.Connector,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccountID,
		&i.MetadataJson,
		&i.ExpiresAt,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorOAuthAttempt = `-- name: GetConnectorOAuthAttempt :one
SELECT connector, state, code_verifier, created_at
FROM connector_oauth_attempts
WHERE connector = ? AND state = ?
`

type GetConnectorOAuthAttemptParams struct {
	Connector string `json:"connector"`
	State     string `json:"state"`
}

type GetConnectorOAuthAttemptRow struct {
	Connector    string `json:"connector"`
	State        string `json:"state"`
	CodeVerifier string `json:"code_verifier"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) GetConnectorOAuthAttempt(ctx context.Context, arg GetConnectorOAuthAttemptParams) (GetConnectorOAuthAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getConnectorOAuthAttempt, arg.Connector, arg.State)
	var i GetConnectorOAuthAttemptRow
	err := row.Scan(
		&i.Connector,
		&i.State,
		&i.CodeVerifier,
		&i.CreatedAt,
	)
	return i, err
}

const upsertConnectorAuth = `-- name: UpsertConnectorAuth :exec
INSERT INTO connector_auth (
    connector,
    access_token,
    refresh_token,
    account_id,
    metadata_json,
    expires_at,
    connected_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(connector) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    account_id = excluded.account_id,
    metadata_json = excluded.metadata_json,
    expires_at = excluded.expires_at,
    connected_at = excluded.connected_at,
    updated_at = excluded.updated_at
`

type UpsertConnectorAuthParams struct {
	Connector    string         `json:"connector"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	AccountID    sql.NullString `json:"account_id"`
	MetadataJson sql.NullString `json:"metadata_json"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	ConnectedAt  int64          `json:"connected_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) UpsertConnectorAuth(ctx context.Context, arg UpsertConnectorAuthParams) error {
	_, err := q.db.ExecContext(ctx, upsertConnectorAuth,
		arg.Connector,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccountID,
		arg.MetadataJson,
		arg.ExpiresAt,
		arg.ConnectedAt,
		arg.UpdatedAt,
	)
	return err
}
