// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, github_owner, github_repo, created_at)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string `json:"id"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.CreatedAt,
	)
	return err
}

const deleteAllProjects = `-- name: DeleteAllProjects :execresult
DELETE FROM projects
`

func (q *Queries) DeleteAllProjects(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAllProjects)
}

const getProjectByRepo = `-- name: GetProjectByRepo :one
SELECT id, github_owner, github_repo, created_at FROM projects WHERE github_repo = ? LIMIT 1
`

func (q *Queries) GetProjectByRepo(ctx context.Context, githubRepo string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByRepo, githubRepo)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CreatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT id, github_owner, github_repo, created_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GithubOwner,
			&i.GithubRepo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentProjects = `-- name: GetRecentProjects :many
SELECT id, github_owner, github_repo, created_at FROM projects ORDER BY created_at DESC LIMIT 5
`

func (q *Queries) GetRecentProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getRecentProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GithubOwner,
			&i.GithubRepo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS(SELECT 1 FROM projects WHERE github_owner = ? AND github_repo = ?)
`

type ProjectExistsParams struct {
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
}

func (q *Queries) ProjectExists(ctx context.Context, arg ProjectExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectExists, arg.GithubOwner, arg.GithubRepo)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
