// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AssignAgent(ctx context.Context, arg AssignAgentParams) error
	CompleteAgentRun(ctx context.Context, arg CompleteAgentRunParams) error
	CreateAgent(ctx context.Context, arg CreateAgentParams) error
	CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) error
	CreateMachine(ctx context.Context, arg CreateMachineParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	DeleteAgent(ctx context.Context, id string) error
	DeleteAgentRunsByTask(ctx context.Context, taskID string) error
	DeleteMachine(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	FailAgentRun(ctx context.Context, arg FailAgentRunParams) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetAgentRun(ctx context.Context, id string) (AgentRun, error)
	GetDefaultMachine(ctx context.Context) (Machine, error)
	GetLatestRunForStep(ctx context.Context, arg GetLatestRunForStepParams) (AgentRun, error)
	GetMachine(ctx context.Context, id string) (Machine, error)
	GetSettings(ctx context.Context) (GetSettingsRow, error)
	GetTask(ctx context.Context, id string) (Task, error)
	ListAgentRunsByTask(ctx context.Context, taskID string) ([]AgentRun, error)
	ListAgentRunsByTaskAndStep(ctx context.Context, arg ListAgentRunsByTaskAndStepParams) ([]AgentRun, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListMachines(ctx context.Context) ([]Machine, error)
	ListMachinesByMode(ctx context.Context, mode string) ([]Machine, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByAssignedAgent(ctx context.Context, assignedAgentID sql.NullString) ([]Task, error)
	ListTasksByMachine(ctx context.Context, machineID string) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	ListTasksByStatusAndMachine(ctx context.Context, arg ListTasksByStatusAndMachineParams) ([]Task, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) error
	UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) error
	UpdateMachineCapabilities(ctx context.Context, arg UpdateMachineCapabilitiesParams) error
	UpdateMachineLastSeen(ctx context.Context, id string) error
	UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error
	UpdateTaskPositionAndStatus(ctx context.Context, arg UpdateTaskPositionAndStatusParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateTaskStatusAndStep(ctx context.Context, arg UpdateTaskStatusAndStepParams) error
	UpdateTaskStep(ctx context.Context, arg UpdateTaskStepParams) error
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error
}

var _ Querier = (*Queries)(nil)
