// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, agent_backend, external_id, backend_session_id, title, message_count, last_message_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	AgentBackend     string         `json:"agent_backend"`
	ExternalID       sql.NullString `json:"external_id"`
	BackendSessionID sql.NullString `json:"backend_session_id"`
	Title            sql.NullString `json:"title"`
	MessageCount     int64          `json:"message_count"`
	LastMessageAt    sql.NullInt64  `json:"last_message_at"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

// Sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.AgentBackend,
		arg.ExternalID,
		arg.BackendSessionID,
		arg.Title,
		arg.MessageCount,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSessionMessage = `-- name: CreateSessionMessage :exec
INSERT INTO session_messages (id, session_id, sequence, role, kind, content, tool_name, tool_call_id, raw_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionMessageParams struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Sequence   int64          `json:"sequence"`
	Role       string         `json:"role"`
	Kind       string         `json:"kind"`
	Content    sql.NullString `json:"content"`
	ToolName   sql.NullString `json:"tool_name"`
	ToolCallID sql.NullString `json:"tool_call_id"`
	RawJson    string         `json:"raw_json"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) CreateSessionMessage(ctx context.Context, arg CreateSessionMessageParams) error {
	_, err := q.db.ExecContext(ctx, createSessionMessage,
		arg.ID,
		arg.SessionID,
		arg.Sequence,
		arg.Role,
		arg.Kind,
		arg.Content,
		arg.ToolName,
		arg.ToolCallID,
		arg.RawJson,
		arg.CreatedAt,
	)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, agent_backend, external_id, backend_session_id, title, message_count, last_message_at, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentBackend,
		&i.ExternalID,
		&i.BackendSessionID,
		&i.Title,
		&i.MessageCount,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByBackendExternal = `-- name: GetSessionByBackendExternal :one
SELECT id, agent_backend, external_id, backend_session_id, title, message_count, last_message_at, created_at, updated_at FROM sessions WHERE agent_backend = ? AND external_id = ?
`

type GetSessionByBackendExternalParams struct {
	AgentBackend string         `json:"agent_backend"`
	ExternalID   sql.NullString `json:"external_id"`
}

func (q *Queries) GetSessionByBackendExternal(ctx context.Context, arg GetSessionByBackendExternalParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByBackendExternal, arg.AgentBackend, arg.ExternalID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentBackend,
		&i.ExternalID,
		&i.BackendSessionID,
		&i.Title,
		&i.MessageCount,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionNextSequence = `-- name: GetSessionNextSequence :one
SELECT CAST(COALESCE(MAX(sequence) + 1, 0) AS INTEGER) as next_sequence
FROM session_messages
WHERE session_id = ?
`

func (q *Queries) GetSessionNextSequence(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionNextSequence, sessionID)
	var next_sequence int64
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const listSessionMessages = `-- name: ListSessionMessages :many
SELECT id, session_id, sequence, role, kind, content, tool_name, tool_call_id, raw_json, created_at FROM session_messages
WHERE session_id = ?
ORDER BY sequence ASC
`

func (q *Queries) ListSessionMessages(ctx context.Context, sessionID string) ([]SessionMessage, error) {
	rows, err := q.db.QueryContext(ctx, listSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMessage{}
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sequence,
			&i.Role,
			&i.Kind,
			&i.Content,
			&i.ToolName,
			&i.ToolCallID,
			&i.RawJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, agent_backend, external_id, backend_session_id, title, message_count, last_message_at, created_at, updated_at FROM sessions
ORDER BY COALESCE(last_message_at, created_at) DESC, created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AgentBackend,
			&i.ExternalID,
			&i.BackendSessionID,
			&i.Title,
			&i.MessageCount,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET backend_session_id = ?, title = ?, last_message_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	BackendSessionID sql.NullString `json:"backend_session_id"`
	Title            sql.NullString `json:"title"`
	LastMessageAt    sql.NullInt64  `json:"last_message_at"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.BackendSessionID,
		arg.Title,
		arg.LastMessageAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSessionBackendSessionID = `-- name: UpdateSessionBackendSessionID :exec
UPDATE sessions
SET backend_session_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionBackendSessionIDParams struct {
	BackendSessionID sql.NullString `json:"backend_session_id"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSessionBackendSessionID(ctx context.Context, arg UpdateSessionBackendSessionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionBackendSessionID, arg.BackendSessionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :exec
UPDATE sessions
SET title = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
