// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getMachineID = `-- name: GetMachineID :one
SELECT machine_id
FROM settings
WHERE id = 1
`

func (q *Queries) GetMachineID(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getMachineID)
	var machine_id sql.NullString
	err := row.Scan(&machine_id)
	return machine_id, err
}

const getMachineJWT = `-- name: GetMachineJWT :one
SELECT machine_jwt
FROM settings
WHERE id = 1
`

func (q *Queries) GetMachineJWT(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getMachineJWT)
	var machine_jwt sql.NullString
	err := row.Scan(&machine_jwt)
	return machine_jwt, err
}

const getSettings = `-- name: GetSettings :one
SELECT openrouter_key, zai_key, anthropic_key, openai_key,
       COALESCE(agent_backend, 'native') as agent_backend,
       COALESCE(provider, 'anthropic') as provider,
       COALESCE(model, 'claude-opus-4-5') as model,
       updated_at
FROM settings WHERE id = 1
`

type GetSettingsRow struct {
	OpenrouterKey sql.NullString `json:"openrouter_key"`
	ZaiKey        sql.NullString `json:"zai_key"`
	AnthropicKey  sql.NullString `json:"anthropic_key"`
	OpenaiKey     sql.NullString `json:"openai_key"`
	AgentBackend  string         `json:"agent_backend"`
	Provider      string         `json:"provider"`
	Model         string         `json:"model"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(
		&i.OpenrouterKey,
		&i.ZaiKey,
		&i.AnthropicKey,
		&i.OpenaiKey,
		&i.AgentBackend,
		&i.Provider,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMachineID = `-- name: UpdateMachineID :exec
UPDATE settings
SET machine_id = ?,
    updated_at = ?
WHERE id = 1
`

type UpdateMachineIDParams struct {
	MachineID sql.NullString `json:"machine_id"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) UpdateMachineID(ctx context.Context, arg UpdateMachineIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineID, arg.MachineID, arg.UpdatedAt)
	return err
}

const updateMachineJWT = `-- name: UpdateMachineJWT :exec
UPDATE settings
SET machine_jwt = ?,
    updated_at = ?
WHERE id = 1
`

type UpdateMachineJWTParams struct {
	MachineJwt sql.NullString `json:"machine_jwt"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) UpdateMachineJWT(ctx context.Context, arg UpdateMachineJWTParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineJWT, arg.MachineJwt, arg.UpdatedAt)
	return err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO settings (
    id,
    openrouter_key,
    zai_key,
    anthropic_key,
    openai_key,
    agent_backend,
    provider,
    model,
    updated_at
) VALUES (
    1,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(id) DO UPDATE SET
    openrouter_key = excluded.openrouter_key,
    zai_key = excluded.zai_key,
    anthropic_key = excluded.anthropic_key,
    openai_key = excluded.openai_key,
    agent_backend = excluded.agent_backend,
    provider = excluded.provider,
    model = excluded.model,
    updated_at = excluded.updated_at
`

type UpsertSettingsParams struct {
	OpenrouterKey sql.NullString `json:"openrouter_key"`
	ZaiKey        sql.NullString `json:"zai_key"`
	AnthropicKey  sql.NullString `json:"anthropic_key"`
	OpenaiKey     sql.NullString `json:"openai_key"`
	AgentBackend  string         `json:"agent_backend"`
	Provider      sql.NullString `json:"provider"`
	Model         sql.NullString `json:"model"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.OpenrouterKey,
		arg.ZaiKey,
		arg.AnthropicKey,
		arg.OpenaiKey,
		arg.AgentBackend,
		arg.Provider,
		arg.Model,
		arg.UpdatedAt,
	)
	return err
}
