// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT openrouter_key, zai_key, anthropic_key, openai_key,
       COALESCE(agent_backend, 'native') as agent_backend,
       COALESCE(provider, 'anthropic') as provider,
       COALESCE(model, 'claude-opus-4-5') as model,
       updated_at
FROM settings WHERE id = 1
`

type GetSettingsRow struct {
	OpenrouterKey sql.NullString `json:"openrouter_key"`
	ZaiKey        sql.NullString `json:"zai_key"`
	AnthropicKey  sql.NullString `json:"anthropic_key"`
	OpenaiKey     sql.NullString `json:"openai_key"`
	AgentBackend  string         `json:"agent_backend"`
	Provider      string         `json:"provider"`
	Model         string         `json:"model"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(
		&i.OpenrouterKey,
		&i.ZaiKey,
		&i.AnthropicKey,
		&i.OpenaiKey,
		&i.AgentBackend,
		&i.Provider,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT OR REPLACE INTO settings (
    id,
    openrouter_key,
    zai_key,
    anthropic_key,
    openai_key,
    agent_backend,
    provider,
    model,
    updated_at
) VALUES (
    1,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type UpsertSettingsParams struct {
	OpenrouterKey sql.NullString `json:"openrouter_key"`
	ZaiKey        sql.NullString `json:"zai_key"`
	AnthropicKey  sql.NullString `json:"anthropic_key"`
	OpenaiKey     sql.NullString `json:"openai_key"`
	AgentBackend  string         `json:"agent_backend"`
	Provider      sql.NullString `json:"provider"`
	Model         sql.NullString `json:"model"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.OpenrouterKey,
		arg.ZaiKey,
		arg.AnthropicKey,
		arg.OpenaiKey,
		arg.AgentBackend,
		arg.Provider,
		arg.Model,
		arg.UpdatedAt,
	)
	return err
}
