// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, repository_id, session_id, title, intent, promoted_snapshot, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID               string         `json:"id"`
	RepositoryID     sql.NullString `json:"repository_id"`
	SessionID        sql.NullString `json:"session_id"`
	Title            string         `json:"title"`
	Intent           string         `json:"intent"`
	PromotedSnapshot sql.NullString `json:"promoted_snapshot"`
	Status           string         `json:"status"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.RepositoryID,
		arg.SessionID,
		arg.Title,
		arg.Intent,
		arg.PromotedSnapshot,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT
    t.id,
    t.repository_id,
    t.session_id,
    t.title,
    t.intent,
    t.promoted_snapshot,
    t.status,
    t.position,
    t.created_at,
    t.updated_at,
    r.full_name as repository_name
FROM tasks t
LEFT JOIN repositories r ON t.repository_id = r.id
WHERE t.id = ?
`

type GetTaskRow struct {
	ID               string         `json:"id"`
	RepositoryID     sql.NullString `json:"repository_id"`
	SessionID        sql.NullString `json:"session_id"`
	Title            string         `json:"title"`
	Intent           string         `json:"intent"`
	PromotedSnapshot sql.NullString `json:"promoted_snapshot"`
	Status           string         `json:"status"`
	Position         sql.NullInt64  `json:"position"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	RepositoryName   sql.NullString `json:"repository_name"`
}

func (q *Queries) GetTask(ctx context.Context, id string) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SessionID,
		&i.Title,
		&i.Intent,
		&i.PromotedSnapshot,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryName,
	)
	return i, err
}

const getTaskBySessionID = `-- name: GetTaskBySessionID :one
SELECT id, repository_id, session_id, title, intent, promoted_snapshot, status, position, created_at, updated_at FROM tasks WHERE session_id = ?
`

func (q *Queries) GetTaskBySessionID(ctx context.Context, sessionID sql.NullString) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskBySessionID, sessionID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.SessionID,
		&i.Title,
		&i.Intent,
		&i.PromotedSnapshot,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, repository_id, session_id, title, intent, promoted_snapshot, status, position, created_at, updated_at FROM tasks
ORDER BY status ASC, position ASC, created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.PromotedSnapshot,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, repository_id, session_id, title, intent, promoted_snapshot, status, position, created_at, updated_at FROM tasks
WHERE status = ?
ORDER BY status ASC, position ASC, created_at DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.PromotedSnapshot,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithRepository = `-- name: ListTasksWithRepository :many
SELECT
    t.id,
    t.repository_id,
    t.session_id,
    t.title,
    t.intent,
    t.promoted_snapshot,
    t.status,
    t.position,
    t.created_at,
    t.updated_at,
    r.full_name as repository_name,
    COALESCE((SELECT m.content FROM messages m WHERE m.task_id = t.id AND m.role = 'assistant' ORDER BY m.created_at DESC LIMIT 1), '') as last_assistant_message
FROM tasks t
LEFT JOIN repositories r ON t.repository_id = r.id
ORDER BY t.status ASC, t.position ASC, t.created_at DESC
`

type ListTasksWithRepositoryRow struct {
	ID                   string         `json:"id"`
	RepositoryID         sql.NullString `json:"repository_id"`
	SessionID            sql.NullString `json:"session_id"`
	Title                string         `json:"title"`
	Intent               string         `json:"intent"`
	PromotedSnapshot     sql.NullString `json:"promoted_snapshot"`
	Status               string         `json:"status"`
	Position             sql.NullInt64  `json:"position"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
	RepositoryName       sql.NullString `json:"repository_name"`
	LastAssistantMessage interface{}    `json:"last_assistant_message"`
}

func (q *Queries) ListTasksWithRepository(ctx context.Context) ([]ListTasksWithRepositoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksWithRepository)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksWithRepositoryRow{}
	for rows.Next() {
		var i ListTasksWithRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.SessionID,
			&i.Title,
			&i.Intent,
			&i.PromotedSnapshot,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryName,
			&i.LastAssistantMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET position = ? WHERE id = ?
`

type UpdateTaskPositionParams struct {
	Position sql.NullInt64 `json:"position"`
	ID       string        `json:"id"`
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition, arg.Position, arg.ID)
	return err
}

const updateTaskPositionAndStatus = `-- name: UpdateTaskPositionAndStatus :exec
UPDATE tasks SET status = ?, position = ? WHERE id = ?
`

type UpdateTaskPositionAndStatusParams struct {
	Status   string        `json:"status"`
	Position sql.NullInt64 `json:"position"`
	ID       string        `json:"id"`
}

func (q *Queries) UpdateTaskPositionAndStatus(ctx context.Context, arg UpdateTaskPositionAndStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPositionAndStatus, arg.Status, arg.Position, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ? WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}

const updateTaskTitleIntent = `-- name: UpdateTaskTitleIntent :exec
UPDATE tasks SET title = ?, intent = ? WHERE id = ?
`

type UpdateTaskTitleIntentParams struct {
	Title  string `json:"title"`
	Intent string `json:"intent"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskTitleIntent(ctx context.Context, arg UpdateTaskTitleIntentParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskTitleIntent, arg.Title, arg.Intent, arg.ID)
	return err
}
