// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artifacts.sql

package sqlc

import (
	"context"
)

const createArtifact = `-- name: CreateArtifact :exec
INSERT INTO artifacts (id, run_id, path, content, version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateArtifactParams struct {
	ID        string `json:"id"`
	RunID     string `json:"run_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) error {
	_, err := q.db.ExecContext(ctx, createArtifact,
		arg.ID,
		arg.RunID,
		arg.Path,
		arg.Content,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteArtifactsByRun = `-- name: DeleteArtifactsByRun :exec
DELETE FROM artifacts WHERE run_id = ?
`

func (q *Queries) DeleteArtifactsByRun(ctx context.Context, runID string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifactsByRun, runID)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, run_id, path, content, version, created_at, updated_at FROM artifacts WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Path,
		&i.Content,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactsByRun = `-- name: GetArtifactsByRun :many
SELECT id, run_id, path, content, version, created_at, updated_at FROM artifacts WHERE run_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetArtifactsByRun(ctx context.Context, runID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Path,
			&i.Content,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByTask = `-- name: GetArtifactsByTask :many
SELECT a.id, a.run_id, a.path, a.content, a.version, a.created_at, a.updated_at FROM artifacts a
JOIN agent_runs ar ON a.run_id = ar.id
WHERE ar.task_id = ?
ORDER BY a.created_at ASC
`

func (q *Queries) GetArtifactsByTask(ctx context.Context, taskID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Path,
			&i.Content,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
