// Code generated by MockGen. DO NOT EDIT.
// Source: internal/agent/llm_caller.go
//
// Generated by this command:
//
//	mockgen -source=internal/agent/llm_caller.go -destination=internal/agent/mock_llm_caller.go -package=agent
//

// Package agent is a generated GoMock package.
package agent

import (
	context "context"
	reflect "reflect"

	tools "github.com/revrost/counterspell/internal/agent/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMCaller is a mock of LLMCaller interface.
type MockLLMCaller struct {
	ctrl     *gomock.Controller
	recorder *MockLLMCallerMockRecorder
	isgomock struct{}
}

// MockLLMCallerMockRecorder is the mock recorder for MockLLMCaller.
type MockLLMCallerMockRecorder struct {
	mock *MockLLMCaller
}

// NewMockLLMCaller creates a new mock instance.
func NewMockLLMCaller(ctrl *gomock.Controller) *MockLLMCaller {
	mock := &MockLLMCaller{ctrl: ctrl}
	mock.recorder = &MockLLMCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMCaller) EXPECT() *MockLLMCallerMockRecorder {
	return m.recorder
}

// Stream mocks base method.
func (m *MockLLMCaller) Stream(ctx context.Context, messages []Message, allTools map[string]tools.Tool, systemPrompt string) (*LLMStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, messages, allTools, systemPrompt)
	ret0, _ := ret[0].(*LLMStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockLLMCallerMockRecorder) Stream(ctx, messages, allTools, systemPrompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockLLMCaller)(nil).Stream), ctx, messages, allTools, systemPrompt)
}
