// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           string      `json:"id"`
	ProfileID    pgtype.Text `json:"profile_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    int64       `json:"created_at"`
}

type MachineAuth struct {
	ID             string      `json:"id"`
	MachineID      string      `json:"machine_id"`
	ProfileID      string      `json:"profile_id"`
	Subdomain      string      `json:"subdomain"`
	TunnelProvider string      `json:"tunnel_provider"`
	TunnelToken    string      `json:"tunnel_token"`
	CreatedAt      int64       `json:"created_at"`
	LastSeenAt     pgtype.Int8 `json:"last_seen_at"`
	IsActive       bool        `json:"is_active"`
}

type MachineRegistry struct {
	ID              string      `json:"id"`
	ProfileID       string      `json:"profile_id"`
	FlyMachineID    string      `json:"fly_machine_id"`
	FlyAppName      string      `json:"fly_app_name"`
	Status          string      `json:"status"`
	Subdomain       string      `json:"subdomain"`
	PublicUrl       string      `json:"public_url"`
	Region          string      `json:"region"`
	VmSize          string      `json:"vm_size"`
	VolumeID        pgtype.Text `json:"volume_id"`
	CreatedAt       int64       `json:"created_at"`
	LastSeenAt      int64       `json:"last_seen_at"`
	LastHeartbeatAt pgtype.Int8 `json:"last_heartbeat_at"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

type PendingOauthLogin struct {
	ID            string `json:"id"`
	State         string `json:"state"`
	CodeChallenge string `json:"code_challenge"`
	RedirectUri   string `json:"redirect_uri"`
	AuthCode      string `json:"auth_code"`
	CreatedAt     int64  `json:"created_at"`
	ExpiresAt     int64  `json:"expires_at"`
}

type Profile struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
	Tier      string `json:"tier"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type QuotaLimit struct {
	Tier                   string `json:"tier"`
	MaxVmCount             int32  `json:"max_vm_count"`
	MaxVmHoursPerMonth     int32  `json:"max_vm_hours_per_month"`
	MaxTasksPerMonth       int32  `json:"max_tasks_per_month"`
	MaxApiRequestsPerMonth int32  `json:"max_api_requests_per_month"`
	CreatedAt              int64  `json:"created_at"`
	UpdatedAt              int64  `json:"updated_at"`
}

type RateLimit struct {
	ID           string `json:"id"`
	ProfileID    string `json:"profile_id"`
	Endpoint     string `json:"endpoint"`
	RequestCount int32  `json:"request_count"`
	WindowStart  int64  `json:"window_start"`
	WindowEnd    int64  `json:"window_end"`
}

type RoutingTable struct {
	Subdomain    string `json:"subdomain"`
	FlyMachineID string `json:"fly_machine_id"`
	FlyUrl       string `json:"fly_url"`
	IsActive     bool   `json:"is_active"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Subscription struct {
	ID                 string      `json:"id"`
	ProfileID          string      `json:"profile_id"`
	StripeSubID        pgtype.Text `json:"stripe_sub_id"`
	Tier               string      `json:"tier"`
	Status             string      `json:"status"`
	CurrentPeriodStart int64       `json:"current_period_start"`
	CurrentPeriodEnd   int64       `json:"current_period_end"`
	CancelAtPeriodEnd  bool        `json:"cancel_at_period_end"`
	CreatedAt          int64       `json:"created_at"`
	UpdatedAt          int64       `json:"updated_at"`
}

type UsageTracking struct {
	ID          string `json:"id"`
	ProfileID   string `json:"profile_id"`
	MachineID   string `json:"machine_id"`
	MetricType  string `json:"metric_type"`
	Quantity    int32  `json:"quantity"`
	RecordedAt  int64  `json:"recorded_at"`
	PeriodStart int64  `json:"period_start"`
	PeriodEnd   int64  `json:"period_end"`
}

type Waitlist struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
