// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CleanupExpiredOAuthLogins(ctx context.Context) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// Machine auth queries
	CreateMachineAuth(ctx context.Context, arg CreateMachineAuthParams) (MachineAuth, error)
	CreateMachineRegistry(ctx context.Context, arg CreateMachineRegistryParams) (MachineRegistry, error)
	// OAuth pending logins queries
	CreatePendingOAuthLogin(ctx context.Context, arg CreatePendingOAuthLoginParams) (PendingOauthLogin, error)
	CreateRoutingTable(ctx context.Context, arg CreateRoutingTableParams) (RoutingTable, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUsageTracking(ctx context.Context, arg CreateUsageTrackingParams) (UsageTracking, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Profile, error)
	DeleteMachineRegistry(ctx context.Context, id string) error
	DeletePendingOAuthLogin(ctx context.Context, state string) error
	DeleteRoutingTable(ctx context.Context, subdomain string) error
	DeleteSubscription(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	EmailExists(ctx context.Context, email string) (bool, error)
	GetMachineAuthByMachineID(ctx context.Context, machineID string) (MachineAuth, error)
	GetMachineAuthBySubdomain(ctx context.Context, subdomain string) (MachineAuth, error)
	GetMachineAuthByUserID(ctx context.Context, profileID string) ([]MachineAuth, error)
	GetMachineRegistryByFlyMachineID(ctx context.Context, flyMachineID string) (MachineRegistry, error)
	GetMachineRegistryByID(ctx context.Context, id string) (MachineRegistry, error)
	GetMachineRegistryBySubdomain(ctx context.Context, subdomain string) (MachineRegistry, error)
	GetMachineRegistryByUserID(ctx context.Context, profileID string) ([]MachineRegistry, error)
	GetPendingOAuthLoginByState(ctx context.Context, state string) (PendingOauthLogin, error)
	GetQuotaLimitByTier(ctx context.Context, tier string) (QuotaLimit, error)
	GetRoutingTableBySubdomain(ctx context.Context, subdomain string) (RoutingTable, error)
	GetSubscriptionByID(ctx context.Context, id string) (Subscription, error)
	GetSubscriptionByUserID(ctx context.Context, profileID string) (Subscription, error)
	GetUsageTrackingByUserIDAndPeriod(ctx context.Context, arg GetUsageTrackingByUserIDAndPeriodParams) ([]UsageTracking, error)
	GetUserByEmail(ctx context.Context, email string) (Profile, error)
	GetUserByID(ctx context.Context, id string) (Profile, error)
	GetUserByUsername(ctx context.Context, username string) (Profile, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListMachineRegistry(ctx context.Context) ([]MachineRegistry, error)
	ListQuotaLimits(ctx context.Context) ([]QuotaLimit, error)
	ListRoutingTable(ctx context.Context) ([]RoutingTable, error)
	ListSubscriptionsByUser(ctx context.Context, profileID string) ([]Subscription, error)
	ListUsageTracking(ctx context.Context) ([]UsageTracking, error)
	Listprofiles(ctx context.Context) ([]Profile, error)
	RevokeMachineAuth(ctx context.Context, machineID string) (MachineAuth, error)
	UpdateMachineAuthLastSeen(ctx context.Context, arg UpdateMachineAuthLastSeenParams) (MachineAuth, error)
	UpdateMachineAuthTunnel(ctx context.Context, arg UpdateMachineAuthTunnelParams) (MachineAuth, error)
	UpdateMachineRegistry(ctx context.Context, arg UpdateMachineRegistryParams) (MachineRegistry, error)
	UpdateMachineRegistryStatus(ctx context.Context, arg UpdateMachineRegistryStatusParams) (MachineRegistry, error)
	UpdatePendingOAuthLoginAuthCode(ctx context.Context, arg UpdatePendingOAuthLoginAuthCodeParams) (PendingOauthLogin, error)
	UpdateRoutingTable(ctx context.Context, arg UpdateRoutingTableParams) (RoutingTable, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Profile, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
