// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/revrost/code/counterspell/internal/views"
	"strings"
)

// Available models - must match llm.Models
var uiModels = []struct {
	ID   string
	Name string
}{
	{"o#anthropic/claude-sonnet-4.5", "Claude Sonnet 4.5"},
	{"o#anthropic/claude-opus-4.5", "Claude Opus 4.5"},
	{"o#google/gemini-3-pro-preview", "Gemini 3 Pro Preview"},
	{"o#google/gemini-3-flash-preview", "Gemini 3 Flash Preview"},
	{"o#openai/gpt-5.2", "GPT 5.2"},
	{"o#openai/gpt-5.1-codex-max", "GPT 5.1 Codex Max"},
	{"zai#glm-4.7", "GLM 4.7"},
}

// getModelsJSON returns JSON array of models for JavaScript
func getModelsJSON() string {
	var parts []string
	for _, m := range uiModels {
		parts = append(parts, fmt.Sprintf(`{"id":"%s","name":"%s"}`, m.ID, m.Name))
	}
	return `[` + strings.Join(parts, ",") + `]`
}

// InputBar is the main task creation input bar at the bottom of the screen
func InputBar(projects map[string]views.UIProject) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"fixed bottom-6 left-4 right-4 z-20 mx-auto max-w-3xl\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ChatInput(ChatInputConfig{
			Mode:        ChatInputModeCreate,
			Placeholder: "What do you want to build?",
		}, projects).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
