// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/revrost/invoker/internal/db (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mock_repository.go -package=db github.com/revrost/invoker/internal/db Repository
//

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"
	time "time"

	sqlc "github.com/revrost/invoker/internal/db/sqlc"
	models "github.com/revrost/invoker/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpiredOAuthLogins mocks base method.
func (m *MockRepository) CleanupExpiredOAuthLogins(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredOAuthLogins", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredOAuthLogins indicates an expected call of CleanupExpiredOAuthLogins.
func (mr *MockRepositoryMockRecorder) CleanupExpiredOAuthLogins(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredOAuthLogins", reflect.TypeOf((*MockRepository)(nil).CleanupExpiredOAuthLogins), ctx)
}

// CreateMachine mocks base method.
func (m *MockRepository) CreateMachine(ctx context.Context, machine *models.MachineRegistry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachine", ctx, machine)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMachine indicates an expected call of CreateMachine.
func (mr *MockRepositoryMockRecorder) CreateMachine(ctx, machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachine", reflect.TypeOf((*MockRepository)(nil).CreateMachine), ctx, machine)
}

// CreateMachineAuth mocks base method.
func (m *MockRepository) CreateMachineAuth(ctx context.Context, auth *MachineAuth) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachineAuth", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMachineAuth indicates an expected call of CreateMachineAuth.
func (mr *MockRepositoryMockRecorder) CreateMachineAuth(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachineAuth", reflect.TypeOf((*MockRepository)(nil).CreateMachineAuth), ctx, auth)
}

// CreatePendingOAuthLogin mocks base method.
func (m *MockRepository) CreatePendingOAuthLogin(ctx context.Context, login *PendingOAuthLogin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingOAuthLogin", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingOAuthLogin indicates an expected call of CreatePendingOAuthLogin.
func (mr *MockRepositoryMockRecorder) CreatePendingOAuthLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingOAuthLogin", reflect.TypeOf((*MockRepository)(nil).CreatePendingOAuthLogin), ctx, login)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, user)
}

// DeletePendingOAuthLogin mocks base method.
func (m *MockRepository) DeletePendingOAuthLogin(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingOAuthLogin", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingOAuthLogin indicates an expected call of DeletePendingOAuthLogin.
func (mr *MockRepositoryMockRecorder) DeletePendingOAuthLogin(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingOAuthLogin", reflect.TypeOf((*MockRepository)(nil).DeletePendingOAuthLogin), ctx, state)
}

// EmailExists mocks base method.
func (m *MockRepository) EmailExists(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailExists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailExists indicates an expected call of EmailExists.
func (mr *MockRepositoryMockRecorder) EmailExists(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailExists", reflect.TypeOf((*MockRepository)(nil).EmailExists), ctx, email)
}

// GetMachineAuthByMachineID mocks base method.
func (m *MockRepository) GetMachineAuthByMachineID(ctx context.Context, machineID string) (*MachineAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineAuthByMachineID", ctx, machineID)
	ret0, _ := ret[0].(*MachineAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineAuthByMachineID indicates an expected call of GetMachineAuthByMachineID.
func (mr *MockRepositoryMockRecorder) GetMachineAuthByMachineID(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineAuthByMachineID", reflect.TypeOf((*MockRepository)(nil).GetMachineAuthByMachineID), ctx, machineID)
}

// GetMachineAuthByUserID mocks base method.
func (m *MockRepository) GetMachineAuthByUserID(ctx context.Context, userID string) ([]*MachineAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineAuthByUserID", ctx, userID)
	ret0, _ := ret[0].([]*MachineAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineAuthByUserID indicates an expected call of GetMachineAuthByUserID.
func (mr *MockRepositoryMockRecorder) GetMachineAuthByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineAuthByUserID", reflect.TypeOf((*MockRepository)(nil).GetMachineAuthByUserID), ctx, userID)
}

// GetMachineAuthBySubdomain mocks base method.
func (m *MockRepository) GetMachineAuthBySubdomain(ctx context.Context, subdomain string) (*MachineAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineAuthBySubdomain", ctx, subdomain)
	ret0, _ := ret[0].(*MachineAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineAuthBySubdomain indicates an expected call of GetMachineAuthBySubdomain.
func (mr *MockRepositoryMockRecorder) GetMachineAuthBySubdomain(ctx, subdomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineAuthBySubdomain", reflect.TypeOf((*MockRepository)(nil).GetMachineAuthBySubdomain), ctx, subdomain)
}

// GetMachineByUserID mocks base method.
func (m *MockRepository) GetMachineByUserID(ctx context.Context, userID string) (*models.MachineRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.MachineRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineByUserID indicates an expected call of GetMachineByUserID.
func (mr *MockRepositoryMockRecorder) GetMachineByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineByUserID", reflect.TypeOf((*MockRepository)(nil).GetMachineByUserID), ctx, userID)
}

// GetPendingOAuthLoginByState mocks base method.
func (m *MockRepository) GetPendingOAuthLoginByState(ctx context.Context, state string) (*PendingOAuthLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOAuthLoginByState", ctx, state)
	ret0, _ := ret[0].(*PendingOAuthLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOAuthLoginByState indicates an expected call of GetPendingOAuthLoginByState.
func (mr *MockRepositoryMockRecorder) GetPendingOAuthLoginByState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOAuthLoginByState", reflect.TypeOf((*MockRepository)(nil).GetPendingOAuthLoginByState), ctx, state)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockRepository) GetUserByUsername(ctx context.Context, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockRepositoryMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockRepository)(nil).GetUserByUsername), ctx, username)
}

// Queries mocks base method.
func (m *MockRepository) Queries() *sqlc.Queries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queries")
	ret0, _ := ret[0].(*sqlc.Queries)
	return ret0
}

// Queries indicates an expected call of Queries.
func (mr *MockRepositoryMockRecorder) Queries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queries", reflect.TypeOf((*MockRepository)(nil).Queries))
}

// RevokeMachineAuth mocks base method.
func (m *MockRepository) RevokeMachineAuth(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMachineAuth", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMachineAuth indicates an expected call of RevokeMachineAuth.
func (mr *MockRepositoryMockRecorder) RevokeMachineAuth(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMachineAuth", reflect.TypeOf((*MockRepository)(nil).RevokeMachineAuth), ctx, machineID)
}

// UpdateMachineAuthLastSeen mocks base method.
func (m *MockRepository) UpdateMachineAuthLastSeen(ctx context.Context, machineID string, lastSeenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineAuthLastSeen", ctx, machineID, lastSeenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMachineAuthLastSeen indicates an expected call of UpdateMachineAuthLastSeen.
func (mr *MockRepositoryMockRecorder) UpdateMachineAuthLastSeen(ctx, machineID, lastSeenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineAuthLastSeen", reflect.TypeOf((*MockRepository)(nil).UpdateMachineAuthLastSeen), ctx, machineID, lastSeenAt)
}

// UpdateMachineAuthTunnel mocks base method.
func (m *MockRepository) UpdateMachineAuthTunnel(ctx context.Context, machineID, tunnelProvider, tunnelToken, subdomain string) (*MachineAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineAuthTunnel", ctx, machineID, tunnelProvider, tunnelToken, subdomain)
	ret0, _ := ret[0].(*MachineAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMachineAuthTunnel indicates an expected call of UpdateMachineAuthTunnel.
func (mr *MockRepositoryMockRecorder) UpdateMachineAuthTunnel(ctx, machineID, tunnelProvider, tunnelToken, subdomain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineAuthTunnel", reflect.TypeOf((*MockRepository)(nil).UpdateMachineAuthTunnel), ctx, machineID, tunnelProvider, tunnelToken, subdomain)
}

// UpdateMachineStatus mocks base method.
func (m *MockRepository) UpdateMachineStatus(ctx context.Context, machineID, status string, lastSeenAt time.Time, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineStatus", ctx, machineID, status, lastSeenAt, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMachineStatus indicates an expected call of UpdateMachineStatus.
func (mr *MockRepositoryMockRecorder) UpdateMachineStatus(ctx, machineID, status, lastSeenAt, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineStatus", reflect.TypeOf((*MockRepository)(nil).UpdateMachineStatus), ctx, machineID, status, lastSeenAt, errorMessage)
}

// UsernameExists mocks base method.
func (m *MockRepository) UsernameExists(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsernameExists", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsernameExists indicates an expected call of UsernameExists.
func (mr *MockRepositoryMockRecorder) UsernameExists(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsernameExists", reflect.TypeOf((*MockRepository)(nil).UsernameExists), ctx, username)
}
